version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - cowrie-var:/cowrie/var/lib/cowrie:ro
      - cowrie-log:/cowrie/logs:ro

volumes:
  cowrie-var:
  cowrie-log: